/** Usernames that cannot be claimed (WebFinger / routes / ops). */
export const RESERVED_USERNAMES = new Set([
  "admin",
  "administrator",
  "api",
  "ap",
  "atom",
  "auth",
  "blog",
  "dashboard",
  "editor",
  "feed",
  "feeds",
  "help",
  "instance",
  "login",
  "logout",
  "mcp",
  "media",
  "null",
  "onboarding",
  "post",
  "posts",
  "public",
  "register",
  "root",
  "rss",
  "search",
  "settings",
  "static",
  "status",
  "support",
  "system",
  "u",
  "undefined",
  "user",
  "users",
  "www",
  "x-log",
  "xlog",
]);

export function isReservedUsername(username: string): boolean {
  return RESERVED_USERNAMES.has(username.trim().toLowerCase());
}
